### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by palango** [raiden-network/status-page#1]
### Stage 1
- [x] Get the code to run (create local API server with the fake data)
- [ ] Add error handling
  - [ ] No errors in console
  - [x] Display a message when backend is not reachable
- [x] Deployment
  - [x] Create a pipeline to compile optimized assets
  - [x] Create a docker setup with a web server and reverse proxy to serve the static files
- [ ] Collect feedback

### Stage 2
- Incorporate feedback
- Add token network visualizations
- ...

**Comment by ellvtr** [comment]
- [ ] Create local mock API server with the fake data.
- [ ] Add error handling (?)
- [ ] Fix missing data display in spite of response from mock api.
- [ ] Fix `length of undefined` errors in browser console.
- [ ] Fix error with `http://localhost:3000/data` in browser console.
- [ ] Fix lacking d3 graphics.

- [ ] Display a message when backend is not reachable.

**Comment by palango** [comment]
> "Add error handling" (I'm not sure I understand @palango ?)

The frontend should handle all failure conditions that we can imagine. I think this is mostly that the REST endpoint is unavailable or returns incorrect json (either malformatted or not matching our schema). These should be nicely handled and not show errors in the console.

**Comment by ellvtr** [comment]
The above is now in a new issue #12

**Comment by palango** [comment]
Most stuff is done, there are open issue for the other stuff.
